use real workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,10 +12,19 @@ on:
 jobs:
   run-pr:
     if: github.event_name == 'pull_request'
-    uses: ./.github/workflows/pr1.yml
+    uses: ./.github/workflows/pr.yml
 
   run-release:
-    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
-    uses: ./.github/workflows/release1.yml
-    with:
-      yarnVersionArgs: ${{ github.event.inputs.yarnVersionArgs }}
+    if: github.event_name == 'workflow_dispatch'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if not on master
+        if: github.ref != 'refs/heads/master'
+        run: |
+          echo "Error: Release workflow can only be triggered on the master branch."
+          exit 1
+      - name: Run release workflow
+        if: github.ref == 'refs/heads/master'
+        uses: ./.github/workflows/release.yml
+        with:
+          yarnVersionArgs: ${{ github.event.inputs.yarnVersionArgs }}
